### ISSUE TITLE
can't build tdisplay-t4.yaml

### ISSUE THREAD

**Issue by lecrams** [landonr/homeThing#101]
When I try to build the tdisplay-t4 example from the command line I returns with an error:

Any suggestions what I am doing wrong?

![image](https://github.com/landonr/homeThing/assets/74721082/ead7b6d6-67cb-4249-9809-578983c58b17)

**Comment by landonr** [comment]
> Note
To use fonts you will need to have the python pillow package installed, as ESPHome uses that package to translate the TrueType and bitmap font files into an internal format. If you’re running this as a Home Assistant add-on or with the official ESPHome docker image, it should already be installed. Otherwise you need to install it using pip install "pillow==10.1.0".

https://esphome.io/components/display/index.html#images

ill update the docs so its more clear
